//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.3603.
// 
namespace LavajatoMobile.WSLavajato {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Service() {
            //this.Url = "http://187.25.140.71/service.asmx";
            this.Url = "http://192.168.56.1/service.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ServicoAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Servico ServicoAdd(Servico servico) {
            object[] results = this.Invoke("ServicoAdd", new object[] {
                        servico});
            return ((Servico)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginServicoAdd(Servico servico, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ServicoAdd", new object[] {
                        servico}, callback, asyncState);
        }
        
        /// <remarks/>
        public Servico EndServicoAdd(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Servico)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ServicoByCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Servico ServicoByCliente(Cliente cliente) {
            object[] results = this.Invoke("ServicoByCliente", new object[] {
                        cliente});
            return ((Servico)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginServicoByCliente(Cliente cliente, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ServicoByCliente", new object[] {
                        cliente}, callback, asyncState);
        }
        
        /// <remarks/>
        public Servico EndServicoByCliente(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Servico)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ServicoByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Servico ServicoByID(Servico servico) {
            object[] results = this.Invoke("ServicoByID", new object[] {
                        servico});
            return ((Servico)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginServicoByID(Servico servico, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ServicoByID", new object[] {
                        servico}, callback, asyncState);
        }
        
        /// <remarks/>
        public Servico EndServicoByID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Servico)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ServicoCriaGrid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ServicoCriaGrid(Servico servico) {
            object[] results = this.Invoke("ServicoCriaGrid", new object[] {
                        servico});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginServicoCriaGrid(Servico servico, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ServicoCriaGrid", new object[] {
                        servico}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndServicoCriaGrid(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ServicoItemDelete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ServicoItemDelete(ServicoItem servicoItem) {
            this.Invoke("ServicoItemDelete", new object[] {
                        servicoItem});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginServicoItemDelete(ServicoItem servicoItem, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ServicoItemDelete", new object[] {
                        servicoItem}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndServicoItemDelete(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ServicoItemAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ServicoItemAdd(ServicoItem servicoItem) {
            this.Invoke("ServicoItemAdd", new object[] {
                        servicoItem});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginServicoItemAdd(ServicoItem servicoItem, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ServicoItemAdd", new object[] {
                        servicoItem}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndServicoItemAdd(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProdutoTipo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Produto[] ProdutoTipo(int categoriaProduto) {
            object[] results = this.Invoke("ProdutoTipo", new object[] {
                        categoriaProduto});
            return ((Produto[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginProdutoTipo(int categoriaProduto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ProdutoTipo", new object[] {
                        categoriaProduto}, callback, asyncState);
        }
        
        /// <remarks/>
        public Produto[] EndProdutoTipo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Produto[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ClienteByPlaca", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente ClienteByPlaca(Cliente cliente) {
            object[] results = this.Invoke("ClienteByPlaca", new object[] {
                        cliente});
            return ((Cliente)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginClienteByPlaca(Cliente cliente, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ClienteByPlaca", new object[] {
                        cliente}, callback, asyncState);
        }
        
        /// <remarks/>
        public Cliente EndClienteByPlaca(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Cliente)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ClienteAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente ClienteAdd(Cliente cliente) {
            object[] results = this.Invoke("ClienteAdd", new object[] {
                        cliente});
            return ((Cliente)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginClienteAdd(Cliente cliente, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ClienteAdd", new object[] {
                        cliente}, callback, asyncState);
        }
        
        /// <remarks/>
        public Cliente EndClienteAdd(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Cliente)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Servico {
        
        private int idField;
        
        private System.DateTime entradaField;
        
        private System.DateTime saidaField;
        
        private decimal subTotalField;
        
        private decimal descontoField;
        
        private decimal totalField;
        
        private string corField;
        
        private int ordemServicoField;
        
        private int deleteField;
        
        private int canceladoField;
        
        private int lavadoField;
        
        private int finalizadoField;
        
        private Usuario usuarioField;
        
        private Cliente clienteField;
        
        private ServicoItem[] servicoItemField;
        
        private FormaPagamento formaPagamentoField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Entrada {
            get {
                return this.entradaField;
            }
            set {
                this.entradaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Saida {
            get {
                return this.saidaField;
            }
            set {
                this.saidaField = value;
            }
        }
        
        /// <remarks/>
        public decimal SubTotal {
            get {
                return this.subTotalField;
            }
            set {
                this.subTotalField = value;
            }
        }
        
        /// <remarks/>
        public decimal Desconto {
            get {
                return this.descontoField;
            }
            set {
                this.descontoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        public string Cor {
            get {
                return this.corField;
            }
            set {
                this.corField = value;
            }
        }
        
        /// <remarks/>
        public int OrdemServico {
            get {
                return this.ordemServicoField;
            }
            set {
                this.ordemServicoField = value;
            }
        }
        
        /// <remarks/>
        public int Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
            }
        }
        
        /// <remarks/>
        public int Cancelado {
            get {
                return this.canceladoField;
            }
            set {
                this.canceladoField = value;
            }
        }
        
        /// <remarks/>
        public int Lavado {
            get {
                return this.lavadoField;
            }
            set {
                this.lavadoField = value;
            }
        }
        
        /// <remarks/>
        public int Finalizado {
            get {
                return this.finalizadoField;
            }
            set {
                this.finalizadoField = value;
            }
        }
        
        /// <remarks/>
        public Usuario Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public Cliente Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        public ServicoItem[] ServicoItem {
            get {
                return this.servicoItemField;
            }
            set {
                this.servicoItemField = value;
            }
        }
        
        /// <remarks/>
        public FormaPagamento FormaPagamento {
            get {
                return this.formaPagamentoField;
            }
            set {
                this.formaPagamentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario {
        
        private int idField;
        
        private string passwordField;
        
        private string loginField;
        
        private string nomeField;
        
        private string enderecoField;
        
        private string numeroField;
        
        private string bairroField;
        
        private string cepField;
        
        private string cidadeField;
        
        private string ufField;
        
        private string emailField;
        
        private string celularField;
        
        private string telefoneField;
        
        private string cpfField;
        
        private string rgField;
        
        private bool deleteField;
        
        private Permissao permissaoField;
        
        private TipoFuncionario tipoFuncionarioField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string Cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        public string RG {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
            }
        }
        
        /// <remarks/>
        public bool Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
            }
        }
        
        /// <remarks/>
        public Permissao Permissao {
            get {
                return this.permissaoField;
            }
            set {
                this.permissaoField = value;
            }
        }
        
        /// <remarks/>
        public TipoFuncionario TipoFuncionario {
            get {
                return this.tipoFuncionarioField;
            }
            set {
                this.tipoFuncionarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Permissao {
        
        private int idField;
        
        private int produtoField;
        
        private int usuarioField;
        
        private int ordemServicoField;
        
        private int servicoField;
        
        private int categoriaProdutoField;
        
        private int relatorioField;
        
        private int caixaField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int Produto {
            get {
                return this.produtoField;
            }
            set {
                this.produtoField = value;
            }
        }
        
        /// <remarks/>
        public int Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public int OrdemServico {
            get {
                return this.ordemServicoField;
            }
            set {
                this.ordemServicoField = value;
            }
        }
        
        /// <remarks/>
        public int Servico {
            get {
                return this.servicoField;
            }
            set {
                this.servicoField = value;
            }
        }
        
        /// <remarks/>
        public int CategoriaProduto {
            get {
                return this.categoriaProdutoField;
            }
            set {
                this.categoriaProdutoField = value;
            }
        }
        
        /// <remarks/>
        public int Relatorio {
            get {
                return this.relatorioField;
            }
            set {
                this.relatorioField = value;
            }
        }
        
        /// <remarks/>
        public int Caixa {
            get {
                return this.caixaField;
            }
            set {
                this.caixaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FormaPagamento {
        
        private int idField;
        
        private string descricaoField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CategoriaProduto {
        
        private int idField;
        
        private string descricaoField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Estoque {
        
        private int idField;
        
        private System.DateTime dataField;
        
        private int minimoField;
        
        private int quantidadeField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public int Minimo {
            get {
                return this.minimoField;
            }
            set {
                this.minimoField = value;
            }
        }
        
        /// <remarks/>
        public int Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Produto {
        
        private int idField;
        
        private string descricaoField;
        
        private int quantidadeField;
        
        private int minimoField;
        
        private decimal precoCompraField;
        
        private decimal valorUnitarioField;
        
        private Estoque estoqueField;
        
        private CategoriaProduto categoriaProdutoField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public int Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        public int Minimo {
            get {
                return this.minimoField;
            }
            set {
                this.minimoField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrecoCompra {
            get {
                return this.precoCompraField;
            }
            set {
                this.precoCompraField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorUnitario {
            get {
                return this.valorUnitarioField;
            }
            set {
                this.valorUnitarioField = value;
            }
        }
        
        /// <remarks/>
        public Estoque Estoque {
            get {
                return this.estoqueField;
            }
            set {
                this.estoqueField = value;
            }
        }
        
        /// <remarks/>
        public CategoriaProduto CategoriaProduto {
            get {
                return this.categoriaProdutoField;
            }
            set {
                this.categoriaProdutoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicoItem {
        
        private int idField;
        
        private int quantidadeField;
        
        private Servico servicoField;
        
        private Produto produtoField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        public Servico Servico {
            get {
                return this.servicoField;
            }
            set {
                this.servicoField = value;
            }
        }
        
        /// <remarks/>
        public Produto Produto {
            get {
                return this.produtoField;
            }
            set {
                this.produtoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Convenio {
        
        private int idField;
        
        private decimal valorField;
        
        private int deleteField;
        
        private string nomeField;
        
        private string enderecoField;
        
        private string numeroField;
        
        private string bairroField;
        
        private string cepField;
        
        private string cidadeField;
        
        private string ufField;
        
        private string emailField;
        
        private string celularField;
        
        private string telefoneField;
        
        private string cpfField;
        
        private string rgField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public decimal Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public int Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string Cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        public string RG {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente {
        
        private int idField;
        
        private string nomeField;
        
        private string corField;
        
        private string placaField;
        
        private string telefoneField;
        
        private string veiculoField;
        
        private string enderecoField;
        
        private string numeroField;
        
        private string bairroField;
        
        private string cepField;
        
        private string cidadeField;
        
        private string ufField;
        
        private string emailField;
        
        private string celularField;
        
        private string cpfField;
        
        private string rgField;
        
        private bool deleteField;
        
        private Convenio convenioField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Cor {
            get {
                return this.corField;
            }
            set {
                this.corField = value;
            }
        }
        
        /// <remarks/>
        public string Placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        public string Veiculo {
            get {
                return this.veiculoField;
            }
            set {
                this.veiculoField = value;
            }
        }
        
        /// <remarks/>
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string Cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        public string RG {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
            }
        }
        
        /// <remarks/>
        public bool Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
            }
        }
        
        /// <remarks/>
        public Convenio Convenio {
            get {
                return this.convenioField;
            }
            set {
                this.convenioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TipoFuncionario {
        
        private int idField;
        
        private string descricaoField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
}
