//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.208
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HenryCorporation.Lavajato.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HenryCorporation.Lavajato.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente apagar o item de pedido.
        /// </summary>
        internal static string Apagar_item_de_pedido {
            get {
                return ResourceManager.GetString("Apagar_item_de_pedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente apagar o item de pedido.
        /// </summary>
        internal static string Apagar_o_item_de_pedido {
            get {
                return ResourceManager.GetString("Apagar_o_item_de_pedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção.
        /// </summary>
        internal static string Atencao {
            get {
                return ResourceManager.GetString("Atencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bin\Debug\.
        /// </summary>
        internal static string BinDebug {
            get {
                return ResourceManager.GetString("BinDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente já existente na base, favor mudar a placa.
        /// </summary>
        internal static string Cliente_já_existente_na_base {
            get {
                return ResourceManager.GetString("Cliente_já_existente_na_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente não Cadastrado, deseja cadastrar?.
        /// </summary>
        internal static string Cliente_não_Cadastrado {
            get {
                return ResourceManager.GetString("Cliente_não_Cadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente salvo com sucesso!.
        /// </summary>
        internal static string Cliente_salvo_com_sucesso {
            get {
                return ResourceManager.GetString("Cliente_salvo_com_sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconto maior que o valor do produto!.
        /// </summary>
        internal static string Desconto_maior_que_valor_produto {
            get {
                return ResourceManager.GetString("Desconto_maior_que_valor_produto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja cancelar a venda.
        /// </summary>
        internal static string Deseja_cancelar_a_venda {
            get {
                return ResourceManager.GetString("Deseja_cancelar_a_venda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente excluir o produto.
        /// </summary>
        internal static string DesejaRealmenteExcluirOProduto {
            get {
                return ResourceManager.GetString("DesejaRealmenteExcluirOProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarrosNoLavajato.
        /// </summary>
        internal static string dsCarroNoLavajato {
            get {
                return ResourceManager.GetString("dsCarroNoLavajato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dsFechamentoCaixa_DataTable1.
        /// </summary>
        internal static string dsFechamentoCaixa {
            get {
                return ResourceManager.GetString("dsFechamentoCaixa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relProdutoAbaixoEstoque_DataTable1.
        /// </summary>
        internal static string dsProdutoAbaixoEstoque {
            get {
                return ResourceManager.GetString("dsProdutoAbaixoEstoque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSet1.
        /// </summary>
        internal static string dsProdutoEstoque {
            get {
                return ResourceManager.GetString("dsProdutoEstoque", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Edit_No {
            get {
                object obj = ResourceManager.GetObject("Edit_No", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor escolher um cliente.
        /// </summary>
        internal static string Favor_escolher_um_cliente {
            get {
                return ResourceManager.GetString("Favor_escolher_um_cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor inserir nome e senha.
        /// </summary>
        internal static string Favor_inserir_nome_e_senha {
            get {
                return ResourceManager.GetString("Favor_inserir_nome_e_senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor preencher todos os campos.
        /// </summary>
        internal static string FavorPreencherTodosOsCampos {
            get {
                return ResourceManager.GetString("FavorPreencherTodosOsCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor selecionar um item.
        /// </summary>
        internal static string FavorSelecionarUmItem {
            get {
                return ResourceManager.GetString("FavorSelecionarUmItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sfdfsd.
        /// </summary>
        internal static string fdsf {
            get {
                return ResourceManager.GetString("fdsf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja fazer venda avulsa?.
        /// </summary>
        internal static string frmCaixa_VendaAvulsa {
            get {
                return ResourceManager.GetString("frmCaixa_VendaAvulsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor inserir uma quantidade valida!.
        /// </summary>
        internal static string Inserir_quantidade_valida {
            get {
                return ResourceManager.GetString("Inserir_quantidade_valida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item deletado com sucesso!.
        /// </summary>
        internal static string Item_deletado {
            get {
                return ResourceManager.GetString("Item_deletado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhem item encontrado!.
        /// </summary>
        internal static string Nenhem_item_encontrado {
            get {
                return ResourceManager.GetString("Nenhem_item_encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhem item selecionado para alteração.
        /// </summary>
        internal static string Nenhem_item_selecionado {
            get {
                return ResourceManager.GetString("Nenhem_item_selecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum ordem servico aberta com esse número!.
        /// </summary>
        internal static string Nenhum_ordem_servico_aberta {
            get {
                return ResourceManager.GetString("Nenhum_ordem_servico_aberta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum servico encontrado.
        /// </summary>
        internal static string Nenhum_servico_encontrado {
            get {
                return ResourceManager.GetString("Nenhum_servico_encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nennhum produto selecionado!.
        /// </summary>
        internal static string NennhumProdutoSelecionado {
            get {
                return ResourceManager.GetString("NennhumProdutoSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordem de Serviço Aberto .
        /// </summary>
        internal static string Ordem_de_Serviço_Aberto {
            get {
                return ResourceManager.GetString("Ordem_de_Serviço_Aberto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum ordem de servico encontrada com esse numero: .
        /// </summary>
        internal static string OrdemServicoNaoEncontrada {
            get {
                return ResourceManager.GetString("OrdemServicoNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\Relatorios\\Lavagens\\CarrosNoLavajato.
        /// </summary>
        internal static string pathCarroNoLavajato {
            get {
                return ResourceManager.GetString("pathCarroNoLavajato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Relatorios\Produto\Produtos.
        /// </summary>
        internal static string pathRDLProdutoEstoque {
            get {
                return ResourceManager.GetString("pathRDLProdutoEstoque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    -.
        /// </summary>
        internal static string Placa_vazia {
            get {
                return ResourceManager.GetString("Placa_vazia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor preencher todos os campos.
        /// </summary>
        internal static string Preencher_todos_os_campos {
            get {
                return ResourceManager.GetString("Preencher_todos_os_campos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Relatorios\Produto\AbaixoEstoque.
        /// </summary>
        internal static string ProdutoAbaixoEstoque {
            get {
                return ResourceManager.GetString("ProdutoAbaixoEstoque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto atualizado com sucesso.
        /// </summary>
        internal static string ProdutoAtualizadoComSucesso {
            get {
                return ResourceManager.GetString("ProdutoAtualizadoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto excluido!.
        /// </summary>
        internal static string ProdutoExcluido {
            get {
                return ResourceManager.GetString("ProdutoExcluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto salvo com sucesso.
        /// </summary>
        internal static string ProdutoSalvoComSucesso {
            get {
                return ResourceManager.GetString("ProdutoSalvoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rptCarrosNoLavajato.rdlc.
        /// </summary>
        internal static string rdlCarroNoLavajato {
            get {
                return ResourceManager.GetString("rdlCarroNoLavajato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rptProdutosEstoque.rdlc.
        /// </summary>
        internal static string rdlProdutoEstoque {
            get {
                return ResourceManager.GetString("rdlProdutoEstoque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VendaPorPeriodo.rdlc.
        /// </summary>
        internal static string rdlVendaPorPeriodo {
            get {
                return ResourceManager.GetString("rdlVendaPorPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\Relatorios\\caixa\\fechamentodecaixa.
        /// </summary>
        internal static string relFechamentoDeCaixa {
            get {
                return ResourceManager.GetString("relFechamentoDeCaixa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relProdutoAbaixoEstoque.rdlc.
        /// </summary>
        internal static string relProdutoAbaixoEstoque {
            get {
                return ResourceManager.GetString("relProdutoAbaixoEstoque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Separador_Placa {
            get {
                return ResourceManager.GetString("Separador_Placa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entre somente com Números.
        /// </summary>
        internal static string SomenteNumeros {
            get {
                return ResourceManager.GetString("SomenteNumeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tamanhoMaximoDaPlaca.
        /// </summary>
        internal static string Tamanho_Maximo_Placa {
            get {
                return ResourceManager.GetString("Tamanho_Maximo_Placa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum usuário encontrado.
        /// </summary>
        internal static string Usuario_nao_encontrado {
            get {
                return ResourceManager.GetString("Usuario_nao_encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veículo já lavado.
        /// </summary>
        internal static string Veiculo_ja_lavado {
            get {
                return ResourceManager.GetString("Veiculo_ja_lavado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venda cancelada com sucesso!.
        /// </summary>
        internal static string Venda_cancelada {
            get {
                return ResourceManager.GetString("Venda_cancelada", resourceCulture);
            }
        }
    }
}
